#------------------------------------------------------------------------------
# usage: Use tutor to enable the hastexo AWS S3 plugin
#------------------------------------------------------------------------------
name: Open edX Tutor k8s enable AWS S3 plugin
description: Github Action to install and enable the Tutor plugin hastexo/tutor-contrib-s3
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  namespace:
    description: 'The Kubernetes namespace to which the Open edX platform environment will be deployed. Example: openedx-prod'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3.5.0

    # Notes: OPENEDX_AWS_ACCESS_KEY, OPENEDX_AWS_SECRET_ACCESS_KEY and S3_STORAGE_BUCKET
    #        are stored in EKS kubernetes secrets, viewable from k9s.
    #        example values:
    #          OPENEDX_AWS_ACCESS_KEY: ABDCE123456789OHBBGQ
    #          OPENEDX_AWS_SECRET_ACCESS_KEY: A123456789srJ8lgel+ABCDEFGHIJKabcdefghijk
    #          S3_STORAGE_BUCKET: yourschool-global-prod-storage
    #          S3_BACKUP_BUCKET: yourschool-global-prod-backup
    #          S3_CUSTOM_DOMAIN: cdn.courses.yourschool.edu
    #          S3_REGION: us-east-1
    #
    # this config depends on a public read-only AWS S3 bucket policy like this:
    # https://github.com/Medality-Health/terraform-openedx/blob/main/components/s3/main.tf#L19
    #
    #      {
    #          "Version": "2012-10-17",
    #          "Statement": [
    #              {
    #                  "Sid": "",
    #                  "Effect": "Allow",
    #                  "Principal": "*",
    #                  "Action": [
    #                      "s3:GetObject*",
    #                      "s3:List*"
    #                  ],
    #                  "Resource": "arn:aws:s3:::prod-yourschool-global-storage/*"
    #              }
    #          ]
    #      }
    #
    - name: fetch S3 secrets from Kubernetes secrets
      id: get-secret
      uses: openedx-actions/tutor-k8s-get-secret@v1.0.0
      with:
        eks-namespace: ${{ inputs.namespace }}
        eks-secret-name: s3-openedx-storage

    #  run: pip install git+https://github.com/cookiecutter-openedx/tutor-contrib-s3.git@v14.0.3
    - name: install plugin
      id: install-plugin
      shell: bash
      run: pip install git+https://github.com/cookiecutter-openedx/tutor-contrib-s3.git


    # TO DO: add these
    # --set S3_HOST="${{ inputs.s3_host }}" \
    # --set S3_PORT="${{ inputs.s3_port }}" \
    # --set S3_USE_SSL="${{ inputs.s3_use_ssl }}" \
    # --set S3_FILE_UPLOAD_BUCKET="${{ inputs.s3_file_upload_bucket }}" || "$S3_STORAGE_BUCKET" \
    # --set S3_PROFILE_IMAGE_BUCKET="${{ inputs.s3_profile_image_bucket }}" || "$S3_STORAGE_BUCKET" \
    # --set S3_GRADE_BUCKET="${{ inputs.s3_grade_bucket }}" || "$S3_STORAGE_BUCKET" \
    # --set S3_PROFILE_IMAGE_CUSTOM_DOMAIN="${{ inputs.s3_profile_image_custom_domain }}" \
    # --set S3_PROFILE_IMAGE_MAX_AGE="${{ inputs.s3_profile_image_max_age }}" \
    # --set S3_ADDRESSING_STYLE="${{ inputs.s3_addressing_style }}" \
    # --set S3_SIGNATURE_VERSION="${{ inputs.s3_signature_version }}" \
    - name: Enable plugin
      shell: bash
      run: |-
        tutor plugins enable s3
        tutor config save --set OPENEDX_AWS_ACCESS_KEY="$OPENEDX_AWS_ACCESS_KEY" \
                          --set OPENEDX_AWS_SECRET_ACCESS_KEY="$OPENEDX_AWS_SECRET_ACCESS_KEY" \
                          --set OPENEDX_AWS_QUERYSTRING_AUTH="False" \
                          --set OPENEDX_AWS_S3_SECURE_URLS="False" \
                          --set OPENEDX_MEDIA_ROOT="openedx/media/" \
                          --set S3_STORAGE_BUCKET="$S3_STORAGE_BUCKET" \
                          --set S3_CUSTOM_DOMAIN="$S3_CUSTOM_DOMAIN" \
                          --set S3_REGION="$S3_REGION" \
